Unable to create process using '"C:\Users\ealbo\AppData\Local\Programs\Python\Python311\python.exe" -W ignore::DeprecationWarning -c "
import runpy
import sys
sys.path = ['C:\\Users\\ealbo\\AppData\\Local\\Temp\\tmpi69f1u0p\\setuptools-65.5.0-py3-none-any.whl', 'C:\\Users\\ealbo\\AppData\\Local\\Temp\\tmpi69f1u0p\\pip-22.3.1-py3-none-any.whl'] + sys.path
sys.argv[1:] = ['install', '--no-cache-dir', '--no-index', '--find-links', 'C:\\Users\\ealbo\\AppData\\Local\\Temp\\tmpi69f1u0p', '--upgrade', 'setuptools', 'pip']
runpy.run_module(\"pip\", run_name=\"__main__\", alter_sys=True)
"'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ealbo\AppData\Local\Programs\Python\Python311\Lib\ensurepip\__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\ealbo\AppData\Local\Programs\Python\Python311\Lib\ensurepip\__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "C:\Users\ealbo\AppData\Local\Programs\Python\Python311\Lib\ensurepip\__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ealbo\AppData\Local\Programs\Python\Python311\Lib\ensurepip\__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ealbo\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\ealbo\\AppData\\Roaming\\pypoetry\\venv\\Scripts\\python.exe', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'C:\\\\Users\\\\ealbo\\\\AppData\\\\Local\\\\Temp\\\\tmpi69f1u0p\\\\setuptools-65.5.0-py3-none-any.whl\', \'C:\\\\Users\\\\ealbo\\\\AppData\\\\Local\\\\Temp\\\\tmpi69f1u0p\\\\pip-22.3.1-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'C:\\\\Users\\\\ealbo\\\\AppData\\\\Local\\\\Temp\\\\tmpi69f1u0p\', \'--upgrade\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 101.

Traceback:

  File "<stdin>", line 923, in main
  File "<stdin>", line 562, in run
